
language: objective-c
osx_image: xcode9.4

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:
    - env
    - locale
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - pod --version
    - pod setup --silent > /dev/null
    - pod repo update --silent
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail

    - echo Check if the library described by the podspec can be built
    - pod lib lint --allow-warnings

    - echo Build as static library
    - xcodebuild build -project SVGKit-iOS.xcodeproj -scheme 'SVGKit-iOS' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c

    - echo Build as dynamic frameworks
    - xcodebuild build clean -project SVGKit-iOS.xcodeproj -scheme 'SVGKitFramework-iOS' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c
    - xcodebuild build clean -project SVGKit-iOS.xcodeproj -scheme 'SVGKitFramework-tvOS' -sdk appletvsimulator -configuration Debug | xcpretty -c
    - xcodebuild build clean -project SVGKit-iOS.xcodeproj -scheme 'SVGKitFramework-OSX' -sdk macosx -configuration Debug | xcpretty -c

    - echo Build the Demo apps
    - xcodebuild build -project Demo-iOS.xcodeproj -scheme 'Demo-iOS' -configuration Debug -destination 'name=iPhone 8' | xcpretty -c
    - xcodebuild build -project Demo-OSX.xcodeproj -scheme 'Demo-OSX' -sdk macosx -configuration Debug | xcpretty -c
